name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install deps and build package
        run: bun install
      - name: Build
        run: bun run build
      - name: Test
        run: bun test --coverage
